name: Release from Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
